### ISSUE TITLE
Add '.inc' file extension

### ISSUE THREAD

**Issue by GabrielFrigo4** [doinkythederp/nasm-language-support#14]
I find it interesting to add the '.inc' file extension as this appears to be one of the file extensions that is used in assembly (inc of include), plus other vs code extensions for assembly have '.inc'.
![image](https://user-images.githubusercontent.com/66432268/200645092-78998cf4-e589-4a5f-b399-d78fb12fdcce.png)

**Comment by lewisfm** [comment]
Added this in version 1.2.0
