### ISSUE TITLE
'int' command isn't being highlighted

### ISSUE THREAD

**Issue by jasondyoungberg** [doinkythederp/nasm-language-support#15]
The `int` command isn't getting highlighted

![image](https://user-images.githubusercontent.com/71162172/201228705-76da9aa1-0470-4de3-a5ba-1223d325c809.png)

**Comment by doinkythederp** [comment]
Got it! I'll fix this when I have the chance.

**Comment by lewisfm** [comment]
Fixed this in 1.2.0
