### ISSUE TITLE
Syntaxx highlighting not working?

### ISSUE THREAD

**Issue by Frityet** [doinkythederp/nasm-language-support#4]
<img width="696" alt="Screen Shot 2022-07-08 at 12 45 34" src="https://user-images.githubusercontent.com/25426233/178060284-09808197-9d9e-4129-b755-8e0202420226.png">
I am using the latest version of this plugin, with latest vscode

**Comment by doinkythederp** [comment]
It's possible your theme doesn't have highlighting for the specifiers used by the extension. Could you reply with the name of your VSCode theme so I can help fix this?

**Comment by doinkythederp** [comment]
Actually, it's probably because of the capitalization. Can you confirm whether it works when everything is lowercase?

**Comment by Frityet** [comment]
Can confirm, works with lowercase

**Comment by Frityet** [comment]
When will this be on the vscode extension?

**Comment by doinkythederp** [comment]
> When will this be on the vscode extension?

@Frityet Sorry I haven't done this yet! I think I'll be able to publish the fix later today.

**Comment by doinkythederp** [comment]
Alright, I've got the latest version published to the VSCode marketplace. You should be able to restart VSCode and see the changes.
